### ISSUE TITLE
make

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#252]
Hey @pckhoi 

I'm receiving the following error message when I run make. Any idea? 

```
Traceback (most recent call last):
  File "/mnt/c/Users/ayyubi/lleads/processing/scripts/write_deps.py", line 224, in <module>
    inputs, outputs = detect_script_input_output(q, args.debug)
  File "/mnt/c/Users/ayyubi/lleads/processing/scripts/write_deps.py", line 121, in detect_script_input_output
    a, b = process_expr(fn_map, stmt, debug)
  File "/mnt/c/Users/ayyubi/lleads/processing/scripts/write_deps.py", line 100, in process_expr
    raise ValueError("unhandled node %s" % ast.dump(node, indent=4))
ValueError: unhandled node Call(
    func=Attribute(
        value=Name(id='post_event', ctx=Load()),
        attr='to_csv',
        ctx=Load()),
    args=[
        Constant(value='match/post_event_hammond_pd_2020_11_06.csv')],
    keywords=[
        keyword(
            arg='index',
            value=Constant(value=False))])
make: *** [Makefile:42: match/data.d] Error 1
```

**Comment by ayyubibrahimi** [comment]
Awesome. Thanks!

**Comment by pckhoi** [comment]
There are errors still. Please approve this first: https://github.com/ppact/processing/pull/254

**Comment by ayyubibrahimi** [comment]
Looks good! Thanks Khoi.

**Comment by ayyubibrahimi** [comment]
Ran into an issue when running dvc checkout. It looks like I deleted the entire `raw` directory, when I believed that I was only deleting unused all unused csv files. I receive the same message when running `dvc checkout` in the new repo as well. Please advise. If this is something that will be addressed as you continue to update the readme, please feel free to ignore and I'll standby.  Thanks!  

```
WARNING: No file hash info found for '/mnt/c/Users/ayyubi/dvc/processing/data/raw'. It won't be created.
ERROR: Checkout failed for following targets:
/mnt/c/Users/ayyubi/dvc/processing/data/raw
Is your cache up to date?
<https://error.dvc.org/missing-files>
```
